version: '3.8'

services:
  tc-analysis:
    image: ytang-tc
    container_name: ytang-tc-container
    build:
         context: .
         dockerfile: Dockerfile.gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OMPI_MCA_btl_vader_single_copy_mechanism=none
    cap_add:
      - SYS_NICE
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./.:/app
      - /mnt/weka/data/git_lfs/pytorch:/data
    working_dir: /app
    stdin_open: true
    tty: true
    shm_size: '10g'  # Added shm_size here

